### ISSUE TITLE
Link to CfEngine reference manual

### ISSUE THREAD

**Issue by bahamat** [bahamat/cf-primer#3]
In slide 41: make "CFEngine Reference Manual" a link !
I think I can see how to do that in this markup language, from the existing links, but I'm not sure which URL you'd use to refer to the reference manual.

**Comment by nickanderson** [comment]
https://docs.cfengine.com/latest/reference.html

Or

https://docs.cfengine.com/lts/reference.html

**Comment by bahamat** [comment]
Fixed in 6cc7954
