### ISSUE TITLE
Policy distribution slide incorrectly shows client copies made from hub "inputs"

### ISSUE THREAD

**Issue by mikeweilgart** [bahamat/cf-primer#5]
Actually, they are copied from "masterfiles" on the hub to "inputs" on the clients (as well as from "masterfiles" on hub to "inputs" on hub).  :)

https://github.com/bahamat/cf-primer/blob/fdd94d0a0261759a60f2e31e1d3031dee5a0ddcf/policy_propagation.dot#L34-L35

https://github.com/cfengine/masterfiles/blob/ec023a33d6943011dcaabf6b192c6cfd2cab276b/cfe_internal/update/update_policy.cf#L40

**Comment by atsaloli** [comment]
Closing issue, as it was fixed by #8
