### ISSUE TITLE
Package management slide shows the packages promise type deprecated as of CFEngine 3.7

### ISSUE THREAD

**Issue by mikeweilgart** [bahamat/cf-primer#6]
https://github.com/bahamat/cf-primer/blob/fdd94d0a0261759a60f2e31e1d3031dee5a0ddcf/cf-primer.md#package-management

https://docs.cfengine.com/docs/3.10/reference-promise-types-packages-deprecated.html

**Comment by bahamat** [comment]
@mikeweilgart Would you be able to update this and provide a pull request?
